### ISSUE TITLE
Bug Found, can't connect to DB

### ISSUE THREAD

**Issue by MastoryMd5** [Begad666/cps#16]
https://hasteb.in/ogoqugux.cs

I'm having issues witht the authentication using mysql, this is the first plugin that encounters this plugin.

 - OS: debian 10
 - Java Version: java 11 amazon corretto
 - Plugin Version: v4.1.1
 - BungeeCord Version: #379

**Comment by Begad666** [comment]
That's probably because the user you are using doesn't use the password authentication (might be unix sockets).
Check if your user uses password authentication (mysql_native_password, mysql_old_password, sha256_password or caching_sha2_password) and if the user uses it, then probably a problem with the plugin.

**Comment by MastoryMd5** [comment]
The user is using caching_sha2_password i compiled your latest version of CoreAPI and It's all fixed, Thanks 💯

**Comment by Begad666** [comment]
But the build isn't working but anyway, no problem.
